import React, { useState } from "react";
import { WrapperRow } from "../styles/stylesheet";
import { Button } from "./Button";

export const ButtonRow = ({
  game,
  pinsDown,
  setPinsDown,
  currentFrameIndex,
  setCurrentFrameIndex,
}) => {
  const [rollCounter, setRollCounter] = useState(0);

  return (
    <WrapperRow>
      {currentFrameIndex}
      <Button
        game={game}
        buttonValue={0}
        pinsDown={pinsDown}
        setPinsDown={setPinsDown}
        currentFrameIndex={currentFrameIndex}
        setCurrentFrameIndex={setCurrentFrameIndex}
        rollCounter={rollCounter}
        setRollCounter={setRollCounter}
      />
      <Button
        game={game}
        buttonValue={1}
        pinsDown={pinsDown}
        setPinsDown={setPinsDown}
        currentFrameIndex={currentFrameIndex}
        setCurrentFrameIndex={setCurrentFrameIndex}
        rollCounter={rollCounter}
        setRollCounter={setRollCounter}
      />
      <Button
        game={game}
        buttonValue={2}
        pinsDown={pinsDown}
        setPinsDown={setPinsDown}
        currentFrameIndex={currentFrameIndex}
        setCurrentFrameIndex={setCurrentFrameIndex}
        rollCounter={rollCounter}
        setRollCounter={setRollCounter}
      />
      <Button
        game={game}
        buttonValue={3}
        pinsDown={pinsDown}
        setPinsDown={setPinsDown}
        currentFrameIndex={currentFrameIndex}
        setCurrentFrameIndex={setCurrentFrameIndex}
        rollCounter={rollCounter}
        setRollCounter={setRollCounter}
      />
      <Button
        game={game}
        buttonValue={4}
        pinsDown={pinsDown}
        setPinsDown={setPinsDown}
        currentFrameIndex={currentFrameIndex}
        setCurrentFrameIndex={setCurrentFrameIndex}
        rollCounter={rollCounter}
        setRollCounter={setRollCounter}
      />
      <Button
        game={game}
        buttonValue={5}
        pinsDown={pinsDown}
        setPinsDown={setPinsDown}
        currentFrameIndex={currentFrameIndex}
        setCurrentFrameIndex={setCurrentFrameIndex}
        rollCounter={rollCounter}
        setRollCounter={setRollCounter}
      />
      <Button
        game={game}
        buttonValue={6}
        pinsDown={pinsDown}
        setPinsDown={setPinsDown}
        currentFrameIndex={currentFrameIndex}
        setCurrentFrameIndex={setCurrentFrameIndex}
        rollCounter={rollCounter}
        setRollCounter={setRollCounter}
      />
      <Button
        game={game}
        buttonValue={7}
        pinsDown={pinsDown}
        setPinsDown={setPinsDown}
        currentFrameIndex={currentFrameIndex}
        setCurrentFrameIndex={setCurrentFrameIndex}
        rollCounter={rollCounter}
        setRollCounter={setRollCounter}
      />
      <Button
        game={game}
        buttonValue={8}
        pinsDown={pinsDown}
        setPinsDown={setPinsDown}
        currentFrameIndex={currentFrameIndex}
        setCurrentFrameIndex={setCurrentFrameIndex}
        rollCounter={rollCounter}
        setRollCounter={setRollCounter}
      />
      <Button
        game={game}
        buttonValue={9}
        pinsDown={pinsDown}
        setPinsDown={setPinsDown}
        currentFrameIndex={currentFrameIndex}
        setCurrentFrameIndex={setCurrentFrameIndex}
        rollCounter={rollCounter}
        setRollCounter={setRollCounter}
      />
      <Button
        game={game}
        buttonValue={10}
        pinsDown={pinsDown}
        setPinsDown={setPinsDown}
        currentFrameIndex={currentFrameIndex}
        setCurrentFrameIndex={setCurrentFrameIndex}
        rollCounter={rollCounter}
        setRollCounter={setRollCounter}
      />
    </WrapperRow>
  );
};
